"""The builds' APKs, shared as assets of one GitHub release so anyone can sideload them on a Quest.

A run lists its APK in run.json as {"apk": {"source": "project/<path>.apk"}}. The file itself stays
out of git (build output); `python3 tools/lab apks` reads its package and app name, records them in
run.json for the report, rewrites the release notes and uploads any APK the release lacks or holds
in another size. The report links to the release asset, so it works without the file.
"""
import glob
import os
import re
import subprocess
import tempfile

import common

TAG = "apks"
TITLE = "Builds for Meta Quest"


def source_path(run_id, apk):
    """An agent's APK sits in the run's project/; one the lab built sits under raw/ (out of git)."""
    if apk["source"].startswith("raw/"):
        return os.path.join(common.ROOT, apk["source"])
    return os.path.join(common.run_dir(run_id), apk["source"])


def asset_name(run_id):
    return f"soaring-{run_id}.apk"


def asset_url(repo_url, run_id):
    return f"{repo_url}/releases/download/{TAG}/{asset_name(run_id)}"


def release_url(repo_url):
    return f"{repo_url}/releases/tag/{TAG}"


def _aapt():
    tools = sorted(glob.glob(os.path.expanduser("~/Library/Android/sdk/build-tools/*/aapt")))
    return tools[-1] if tools else None


def describe(path):
    """Package, version and app name of an APK (empty when the Android build tools are missing)."""
    aapt = _aapt()
    if not aapt:
        return {}
    out = subprocess.run([aapt, "dump", "badging", path], capture_output=True, text=True).stdout
    package = re.search(r"^package: name='([^']+)'.*?versionName='([^']*)'", out, re.M)
    label = re.search(r"^application-label:'([^']*)'", out, re.M)
    info = {}
    if package:
        info.update(package=package.group(1), version=package.group(2))
    if label:
        info["label"] = label.group(1)
    return info


def _gh(*args, check=True):
    return subprocess.run(["gh", *args], capture_output=True, text=True, check=check)


def _credits(run_id):
    """Third-party credits files in a build, for the release notes."""
    project = os.path.join(common.run_dir(run_id), "project")
    found = []
    for pattern in ("CREDITS.md", "docs/CREDITS.md", "THIRD_PARTY_NOTICES.*", "docs/THIRD_PARTY.md", "*/Assets/**/AudioCredits.txt"):
        found += sorted(glob.glob(os.path.join(project, pattern), recursive=True))
    return [os.path.relpath(f, common.ROOT) for f in found]


def release_notes(entries, repo_url):
    rows, lab = [], []
    for run_id, run in entries:
        apk = run["apk"]
        mark = " *" if apk.get("by") == "lab" else ""
        if mark:
            lab.append(f"\\* {run['title']}: {apk.get('note', 'built by the lab, not by its agent.')}")
        rows.append(f"| [{run['title']}]({repo_url}/tree/main/runs/{run_id}){mark} | `{asset_name(run_id)}` | "
                    f"{apk.get('label', '?')} | `{apk.get('package', '?')}` | {apk.get('built', '?')} | "
                    f"{apk.get('bytes', 0) / 1048576:.0f} MB |")
    credits = []
    for run_id, run in entries:
        files = _credits(run_id)
        if files:
            credits.append(f"- {run['title']}: " + ", ".join(f"[{os.path.basename(f)}]({repo_url}/blob/main/{f})" for f in files))
    site = repo_url.split("github.com/")[-1].split("/")
    return "\n".join([
        "The builds in the Soaring LLM Lab as APKs, debug-signed, for sideloading on a Meta Quest. Each is exactly "
        "as its agent built it, except where marked *. They are experiments, not store apps.",
        "",
        f"How each one was made and what it cost: https://{site[0].lower()}.github.io/{site[1]}/",
        "",
        "## Install",
        "",
        "1. Turn on developer mode for the headset (Meta Horizon app on your phone: Devices → your headset → "
        "Developer mode; it asks you to set up a free developer account).",
        "2. Connect the headset over USB and allow USB debugging when it asks.",
        "3. `adb install -r <file>.apk`, or drag the file into SideQuest.",
        "4. On the headset: Library → Unknown Sources.",
        "",
        "Builds with different packages install side by side. Several call themselves just \"Soaring\" on the "
        "headset, so tell them apart by package in Settings → Apps.",
        "",
        "| Build | File | Name on the headset | Package | Built | Size |",
        "|---|---|---|---|---|---|",
        *rows,
        "",
        *([*lab, ""] if lab else []),
        "## Credits",
        "",
        "Built with Godot or Unity and the Godot OpenXR Vendors plugin or Meta's XR packages. Third-party "
        "sounds, fonts and art in these builds are credited in their projects:",
        "",
        *(credits or ["- none listed"]),
        "",
        f"_Generated by `python3 tools/lab apks`._",
    ])


def publish(run_ids, dry_run=False):
    repo_url = common.repo_url()
    if not repo_url:
        raise SystemExit("apks: the origin remote is not on GitHub")
    repo = repo_url.split("github.com/")[-1]
    entries = []
    for run_id in run_ids:
        path = os.path.join(common.run_dir(run_id), "run.json")
        run = common.load_json(path)
        apk = run.get("apk")
        if not apk or run.get("excluded"):
            continue
        source = source_path(run_id, apk)
        if not os.path.exists(source):
            print(f"  {run_id}: {apk['source']} is missing, skipped")
            continue
        updated = dict(apk, **describe(source), bytes=os.path.getsize(source),
                       built=common.local(common.dt.datetime.fromtimestamp(os.path.getmtime(source), common.dt.timezone.utc)).strftime("%Y-%m-%d %H:%M"))
        if updated != apk:
            run["apk"] = updated
            common.save_json(path, run)
        entries.append((run_id, run))
    if dry_run:
        print(release_notes(entries, repo_url))
        return
    with tempfile.TemporaryDirectory() as tmp:
        notes = os.path.join(tmp, "notes.md")
        with open(notes, "w", encoding="utf-8") as f:
            f.write(release_notes(entries, repo_url))
        view = _gh("release", "view", TAG, "-R", repo, "--json", "assets", "--jq", ".assets[] | \"\\(.name) \\(.size)\"", check=False)
        if view.returncode != 0:
            _gh("release", "create", TAG, "-R", repo, "--title", TITLE, "--notes-file", notes, "--target", "main")
            uploaded = {}
        else:
            _gh("release", "edit", TAG, "-R", repo, "--title", TITLE, "--notes-file", notes)
            uploaded = dict(line.rsplit(" ", 1) for line in view.stdout.splitlines() if line.strip())
        for run_id, run in entries:
            name, size = asset_name(run_id), run["apk"]["bytes"]
            if uploaded.get(name) == str(size):
                print(f"  {run_id}: up to date")
                continue
            link = os.path.join(tmp, name)
            os.symlink(source_path(run_id, run["apk"]), link)
            _gh("release", "upload", TAG, link, "-R", repo, "--clobber")
            print(f"  {run_id}: uploaded {name} ({size / 1048576:.0f} MB)")
    print(f"  {release_url(repo_url)}")
